import type { LanguageEmailCopy } from './types.js'

/** German (formal "Sie") — keys must match en.ts exactly (emailCopy.test.ts). */
export const de: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "Bestanden: {quiz_title} – {score} %",
      "t_tagline": "B2B-Partnerportal",
      "t_badge": "Modul abgeschlossen",
      "t_heading": "Gut gemacht, {user_name}!",
      "t_intro_before": "Sie haben das Modul",
      "t_intro_middle": "mit einem Ergebnis von",
      "t_intro_after": " bestanden. Weiter so – Sie sind einen Schritt näher dran, Sliquid Certified Expert zu werden.",
      "t_label_module": "Modul",
      "t_label_score": "Ergebnis",
      "t_cta": "Schulung fortsetzen →",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_cert_issued": {
      "t_subject": "Ihr Sliquid Certified Expert-Zertifikat",
      "t_tagline": "B2B-Partnerportal",
      "t_heading": "Sie sind Sliquid Certified Expert!",
      "t_intro_before": "Herzlichen Glückwunsch,",
      "t_intro_after": "! Sie haben den gesamten Sliquid Certified Expert Training Course erfolgreich abgeschlossen. Ihr Zertifikat wurde ausgestellt und steht in Ihrem Portal zum Download bereit.",
      "t_label_issued_to": "Ausgestellt für",
      "t_label_completed": "Abgeschlossen",
      "t_label_cert_number": "Zertifikatsnummer",
      "t_cta": "Zertifikat ansehen & herunterladen",
      "t_verify": "Sie können dieses Zertifikat jederzeit auch hier überprüfen:",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_register_confirm": {
      "t_subject": "Ihre Registrierung beim Sliquid B2B-Portal",
      "t_tagline": "B2B-Partnerportal",
      "t_heading": "Willkommen, {user_name}!",
      "t_intro_before": "Vielen Dank für Ihre Registrierung beim",
      "t_intro_after": ". Ihr Konto ist eingegangen und wird derzeit von unserem Team geprüft.",
      "t_badge": "In Prüfung",
      "t_pending": "Unser Team prüft Ihre Bewerbung und schaltet den Portalzugang in Kürze frei. Sobald Ihr Konto freigegeben ist, erhalten Sie eine Bestätigungs-E-Mail.",
      "t_details_heading": "Ihre Registrierungsdaten",
      "t_label_name": "Name",
      "t_label_email": "E-Mail",
      "t_help": "Bei Fragen in der Zwischenzeit erreichen Sie uns jederzeit unter",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_approved": {
      "t_subject": "Ihr Konto beim Sliquid B2B-Portal ist freigegeben",
      "t_tagline": "B2B-Partnerportal",
      "t_badge": "Konto freigegeben",
      "t_heading": "Sie sind dabei, {user_name}!",
      "t_intro": "Ihr Konto beim Sliquid B2B-Partnerportal wurde freigegeben. Sie können sich jetzt anmelden und auf alle Ressourcen Ihres Kontotyps zugreifen.",
      "t_label_role": "Kontotyp",
      "t_cta": "Beim Portal anmelden →",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_declined": {
      "t_subject": "Neuigkeiten zu Ihrer Bewerbung beim Sliquid B2B-Portal",
      "t_tagline": "B2B-Partnerportal",
      "t_heading": "Neuigkeiten zu Ihrer Bewerbung",
      "t_intro": "Hallo {user_name}, vielen Dank für Ihr Interesse am Sliquid B2B-Partnerportal. Nach Prüfung Ihrer Bewerbung können wir Ihnen derzeit leider keinen Portalzugang gewähren.",
      "t_body": "Falls Sie glauben, dass es sich um einen Irrtum handelt, oder Ihre Bewerbung besprechen möchten, wenden Sie sich bitte an unser Support-Team – wir helfen Ihnen gern.",
      "t_cta": "Support kontaktieren",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_reward_confirm": {
      "t_subject": "Ihre Sliquid-Belohnung ist unterwegs!",
      "t_tagline": "B2B-Partnerportal",
      "t_badge": "Belohnung angefordert",
      "t_heading": "Ihre Belohnung ist unterwegs, {user_name}!",
      "t_intro": "Wir haben Ihre Anforderung erhalten. Unser Team bearbeitet sie und versendet Ihre Artikel an die hinterlegte Adresse. Achten Sie auf eine Versandbenachrichtigung in Ihrem Postfach.",
      "t_label_product": "Kostenloses Produkt",
      "t_label_shirt": "T-Shirt-Größe",
      "t_label_ship_to": "Lieferadresse",
      "t_update_before": "Müssen Sie Ihre Lieferadresse ändern? Wenden Sie sich so bald wie möglich an",
      "t_update_after": ".",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_marketing_user": {
      "t_subject": "Ihre Anfrage nach Werbematerial ist eingegangen",
      "t_tagline": "B2B-Partnerportal",
      "t_badge": "Anfrage eingegangen",
      "t_heading": "Ihre Anfrage ist da, {user_name}!",
      "t_intro": "Ihre Marketinganfrage wurde übermittelt. Unser Team prüft sie und meldet sich, um die Details zu bestätigen.",
      "t_label_items": "Angeforderte Artikel",
      "t_help": "Fragen zu Ihrer Anfrage? Schreiben Sie an",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_medical_user": {
      "t_subject": "Ihre Anfrage nach medizinischem Marketingmaterial ist eingegangen",
      "t_tagline": "Programm für medizinisches Fachpersonal",
      "t_badge": "Anfrage eingegangen",
      "t_heading": "Ihre Anfrage ist da, {user_name}!",
      "t_intro": "Ihre Anfrage nach medizinischem Marketingmaterial wurde übermittelt. Unser Team für medizinisches Fachpersonal prüft sie und meldet sich, um Lieferung und Versanddetails zu bestätigen.",
      "t_label_items": "Angeforderte Artikel",
      "t_help": "Fragen zu Ihrer Anfrage? Schreiben Sie an",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "portal_password_reset": {
      "t_subject": "Passwort für das Sliquid-Partnerportal zurücksetzen",
      "t_tagline": "Partnerportal",
      "t_heading": "Passwort zurücksetzen",
      "t_greeting": "Hallo {user_name},",
      "t_intro": "Wir haben eine Anfrage zum Zurücksetzen des Passworts für Ihr Konto im Sliquid-Partnerportal erhalten. Klicken Sie auf die Schaltfläche unten, um ein neues Passwort festzulegen.",
      "t_cta": "Passwort zurücksetzen",
      "t_expiry_before": "Dieser Link ist",
      "t_expiry_duration": "1 Stunde",
      "t_expiry_after": " gültig. Wenn Sie ihn nicht rechtzeitig verwenden, müssen Sie einen neuen anfordern.",
      "t_fallback": "Falls die Schaltfläche nicht funktioniert, kopieren Sie diese URL in Ihren Browser:",
      "t_ignore": "Wenn Sie kein Zurücksetzen des Passworts angefordert haben, können Sie diese E-Mail einfach ignorieren – Ihr Passwort bleibt unverändert.",
      "t_confidential": "Sliquid-Partnerportal – Vertraulich",
      "t_rights": "Alle Rechte vorbehalten."
    },
    "portal_asset_broadcast": {
      "t_subject": "Neu in der Sliquid-Produktbibliothek: {asset_name}",
      "t_tagline": "B2B-Partnerportal",
      "t_badge": "Neu in der Produktbibliothek",
      "t_heading": "Neue Inhalte für Sie, {user_name}!",
      "t_intro": "In Ihrer Produktbibliothek sind neue Inhalte verfügbar. Öffnen Sie das Portal, um sie anzusehen und für Ihr Geschäft herunterzuladen.",
      "t_label_asset": "Inhalt",
      "t_label_brand": "Marke",
      "t_cta": "Produktbibliothek ansehen →",
      "t_footer_sent": "Diese E-Mail wurde vom Sliquid B2B-Partnerportal gesendet.",
      "t_footer_questions": "Fragen? Kontakt:"
    },
    "b2b_contact_reply": {
      "t_subject": "Wir haben Ihre Nachricht erhalten – Sliquid",
      "t_tagline": "B2B-Partnerschaften",
      "t_heading": "Danke für Ihre Nachricht, {to_name}!",
      "t_intro_before": "Wir haben Ihre Nachricht erhalten, und ein Mitglied unseres B2B-Teams prüft sie in Kürze. In der Regel antworten wir innerhalb von",
      "t_intro_duration": "2 Werktagen",
      "t_portal": "In der Zwischenzeit können Sie gern unser Partnerportal erkunden – dort finden Sie Produktinformationen, Marketingmaterial und Schulungsressourcen.",
      "t_cta": "Partnerportal besuchen",
      "t_next_heading": "So geht es weiter",
      "t_step1": "Unser Team prüft Ihre Anfrage und leitet sie an den richtigen Ansprechpartner weiter.",
      "t_step2": "Wir melden uns per E-Mail (oder telefonisch, falls Sie eine Nummer angegeben haben).",
      "t_step3": "Sie erhalten ein individuelles Angebot oder eine Rückmeldung passend zu Ihrer Anfrage.",
      "t_footer_reply": "Fragen? Antworten Sie auf diese E-Mail oder wenden Sie sich an",
      "t_rights": "Alle Rechte vorbehalten."
    },
    "b2b_retailer_confirm": {
      "t_subject": "Ihre Bewerbung als Sliquid-Händler / -Vertriebspartner",
      "t_tagline": "Programm für Händler & Vertriebspartner",
      "t_badge": "Bewerbung eingegangen",
      "t_heading": "Danke für Ihre Bewerbung, {contact_name}!",
      "t_intro_before": "Wir haben Ihre Bewerbung für",
      "t_intro_after": "als Sliquid-Händler oder -Vertriebspartner erhalten. Ein Mitglied unseres Vertriebsteams prüft Ihre Angaben und meldet sich in Kürze bei Ihnen.",
      "t_label_brands": "Ausgewählte Marken",
      "t_next_heading": "So geht es weiter",
      "t_step1_before": "Unser Vertriebsteam prüft Ihre Bewerbung – in der Regel innerhalb von",
      "t_step1_duration": "2–3 Werktagen",
      "t_step2": "Wir melden uns per E-Mail oder telefonisch, um die nächsten Schritte zu besprechen und Ihre Fragen zu beantworten.",
      "t_step3": "Nach der Freigabe erhalten Sie Zugang zum Sliquid B2B-Partnerportal mit Bestell-, Schulungs- und Marketingressourcen.",
      "t_cta": "Mehr über Sliquid B2B erfahren",
      "t_help": "Fragen in der Zwischenzeit? Kontaktieren Sie unser Vertriebsteam unter",
      "t_submitted": "Gesendet über",
      "t_rights": "Alle Rechte vorbehalten."
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "Danke für Ihre Rückmeldung, {contact_name} – {reference_number}",
      "t_tagline": "Partner-Rückmeldung",
      "t_reference": "Referenz",
      "t_heading": "Vielen Dank, {contact_name}.",
      "t_intro_before": "Wir haben Ihre Rückmeldung für",
      "t_intro_after": "erhalten – und vor allem: Danke für den Platz in Ihrem Regal. Partner wie Sie sind der Grund, warum eine kleine Marke, die von ihren Inhaltsstoffen besessen ist, zwanzig Jahre bestehen konnte.",
      "t_followup": "meldet sich in Kürze bei Ihnen.",
      "t_asked_heading": "Worum Sie uns gebeten haben",
      "t_next_heading": "So geht es weiter",
      "t_step1_before": "Ihr Ansprechpartner prüft die Rückmeldung – in der Regel innerhalb von",
      "t_step1_duration": "1–2 Werktagen",
      "t_step2": "Alles, worum Sie gebeten haben – Marketingmaterial, Produktbilder, Schulungen – wird Ihnen zugeschickt.",
      "t_step3_before": "Geben Sie",
      "t_step3_after": "in jeder Antwort an, dann finden wir Ihre Rückmeldung sofort.",
      "t_cta": "Partnerportal öffnen",
      "t_help": "Brauchen Sie etwas früher? Schreiben Sie an",
      "t_submitted": "Gesendet über",
      "t_rights": "Alle Rechte vorbehalten."
    }
  },
  "roleLabels": {
    "tier1": "Mitarbeiter im Einzelhandel",
    "tier2": "Einzelhandelsleitung",
    "tier3": "Vertriebspartner",
    "tier4": "Interessent",
    "tier5": "Administrator",
    "tier6": "Medizinischer Partner",
    "tier7": "Medien",
    "tier8": "Recht (nur Lesen)"
  },
  "defaults": {
    "pointOfContact": "Ein Mitglied unseres Vertriebsteams",
    "interests": "Keine Auswahl"
  }
}
