import type { LanguageEmailCopy } from './types.js'

/** Spanish (neutral Latin American, formal "usted") — keys must match en.ts exactly (emailCopy.test.ts). */
export const es: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "Aprobó {quiz_title}: {score}%",
      "t_tagline": "Portal de Socios B2B",
      "t_badge": "Módulo completado",
      "t_heading": "¡Buen trabajo, {user_name}!",
      "t_intro_before": "Aprobó el módulo",
      "t_intro_middle": "con una puntuación de",
      "t_intro_after": ". Siga así: está un paso más cerca de convertirse en Experto Certificado Sliquid.",
      "t_label_module": "Módulo",
      "t_label_score": "Puntuación",
      "t_cta": "Continuar la capacitación →",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_cert_issued": {
      "t_subject": "Su certificado de Experto Certificado Sliquid",
      "t_tagline": "Portal de Socios B2B",
      "t_heading": "¡Ya es Experto Certificado Sliquid!",
      "t_intro_before": "Felicidades,",
      "t_intro_after": ". Completó con éxito todo el Curso de Capacitación de Experto Certificado Sliquid. Su certificado fue emitido y está listo para descargarse desde su portal.",
      "t_label_issued_to": "Emitido a",
      "t_label_completed": "Completado",
      "t_label_cert_number": "Número de certificado",
      "t_cta": "Ver y descargar el certificado",
      "t_verify": "También puede verificar este certificado en cualquier momento en",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_register_confirm": {
      "t_subject": "Su registro en el Portal B2B de Sliquid",
      "t_tagline": "Portal de Socios B2B",
      "t_heading": "¡Bienvenido, {user_name}!",
      "t_intro_before": "Gracias por registrarse en el",
      "t_intro_after": ". Recibimos su cuenta y nuestro equipo la está revisando.",
      "t_badge": "Pendiente de revisión",
      "t_pending": "Nuestro equipo revisará su solicitud y le dará acceso al portal en breve. Recibirá un correo de confirmación cuando su cuenta sea aprobada.",
      "t_details_heading": "Datos de su registro",
      "t_label_name": "Nombre",
      "t_label_email": "Correo electrónico",
      "t_help": "Si tiene preguntas mientras tanto, no dude en escribirnos a",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_approved": {
      "t_subject": "Su cuenta del Portal B2B de Sliquid fue aprobada",
      "t_tagline": "Portal de Socios B2B",
      "t_badge": "Cuenta aprobada",
      "t_heading": "¡Ya tiene acceso, {user_name}!",
      "t_intro": "Su cuenta del Portal de Socios B2B de Sliquid fue aprobada. Ya puede iniciar sesión y acceder a todos los recursos disponibles para su tipo de cuenta.",
      "t_label_role": "Tipo de cuenta",
      "t_cta": "Iniciar sesión en su portal →",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_declined": {
      "t_subject": "Novedades sobre su solicitud al Portal B2B de Sliquid",
      "t_tagline": "Portal de Socios B2B",
      "t_heading": "Novedades sobre su solicitud",
      "t_intro": "Hola, {user_name}: gracias por su interés en el Portal de Socios B2B de Sliquid. Tras revisar su solicitud, por ahora no podemos aprobar el acceso al portal.",
      "t_body": "Si cree que se trata de un error o desea hablar sobre su solicitud, comuníquese con nuestro equipo de soporte; con gusto le ayudaremos.",
      "t_cta": "Contactar a soporte",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_reward_confirm": {
      "t_subject": "¡Su recompensa de Sliquid va en camino!",
      "t_tagline": "Portal de Socios B2B",
      "t_badge": "Recompensa enviada",
      "t_heading": "¡Su recompensa va en camino, {user_name}!",
      "t_intro": "Recibimos su solicitud de recompensa. Nuestro equipo procesará su pedido y enviará los artículos a la dirección registrada. Esté atento a su bandeja de entrada: le avisaremos cuando se envíe.",
      "t_label_product": "Producto gratis",
      "t_label_shirt": "Talla de camiseta",
      "t_label_ship_to": "Enviar a",
      "t_update_before": "¿Necesita actualizar su dirección de envío? Escriba a",
      "t_update_after": "lo antes posible.",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_marketing_user": {
      "t_subject": "Recibimos su solicitud de materiales de marketing",
      "t_tagline": "Portal de Socios B2B",
      "t_badge": "Solicitud recibida",
      "t_heading": "¡Recibimos su solicitud, {user_name}!",
      "t_intro": "Su solicitud de marketing fue enviada. Nuestro equipo la revisará y se comunicará con usted para confirmar los detalles.",
      "t_label_items": "Artículos solicitados",
      "t_help": "¿Preguntas sobre su solicitud? Escríbanos a",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_medical_user": {
      "t_subject": "Recibimos su solicitud de marketing médico",
      "t_tagline": "Programa para Profesionales de la Salud",
      "t_badge": "Solicitud recibida",
      "t_heading": "¡Recibimos su solicitud, {user_name}!",
      "t_intro": "Su solicitud de materiales de marketing médico fue enviada. Nuestro equipo para profesionales de la salud la revisará y se comunicará con usted para confirmar la entrega y los detalles de envío.",
      "t_label_items": "Artículos solicitados",
      "t_help": "¿Preguntas sobre su solicitud? Escríbanos a",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "portal_password_reset": {
      "t_subject": "Restablezca su contraseña del Portal de Socios de Sliquid",
      "t_tagline": "Portal de Socios",
      "t_heading": "Restablezca su contraseña",
      "t_greeting": "Hola, {user_name}:",
      "t_intro": "Recibimos una solicitud para restablecer la contraseña de su cuenta del Portal de Socios de Sliquid. Haga clic en el botón de abajo para elegir una nueva contraseña.",
      "t_cta": "Restablecer contraseña",
      "t_expiry_before": "Este enlace vence en",
      "t_expiry_duration": "1 hora",
      "t_expiry_after": ". Si no lo usa a tiempo, deberá solicitar uno nuevo.",
      "t_fallback": "Si el botón no funciona, copie y pegue esta dirección en su navegador:",
      "t_ignore": "Si no solicitó restablecer su contraseña, puede ignorar este correo: su contraseña no cambiará.",
      "t_confidential": "Portal de Socios de Sliquid — Confidencial",
      "t_rights": "Todos los derechos reservados."
    },
    "portal_asset_broadcast": {
      "t_subject": "Nuevo en la Biblioteca de Productos de Sliquid: {asset_name}",
      "t_tagline": "Portal de Socios B2B",
      "t_badge": "Nuevo en la Biblioteca de Productos",
      "t_heading": "¡Hay recursos nuevos, {user_name}!",
      "t_intro": "Hay contenido nuevo disponible en su Biblioteca de Productos. Visite el portal para verlo y descargarlo para su tienda.",
      "t_label_asset": "Recurso",
      "t_label_brand": "Marca",
      "t_cta": "Ver la Biblioteca de Productos →",
      "t_footer_sent": "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      "t_footer_questions": "¿Preguntas? Escriba a"
    },
    "b2b_contact_reply": {
      "t_subject": "Recibimos su mensaje — Sliquid",
      "t_tagline": "Alianzas B2B",
      "t_heading": "¡Gracias por escribirnos, {to_name}!",
      "t_intro_before": "Recibimos su mensaje y un miembro de nuestro equipo B2B lo revisará en breve. Normalmente respondemos en un plazo de",
      "t_intro_duration": "2 días hábiles",
      "t_portal": "Mientras tanto, puede explorar nuestro portal de socios, donde encontrará información de productos, materiales de marketing y recursos de capacitación.",
      "t_cta": "Visitar el portal de socios",
      "t_next_heading": "Próximos pasos",
      "t_step1": "Nuestro equipo revisa su consulta y la asigna al contacto adecuado.",
      "t_step2": "Nos comunicaremos con usted por correo electrónico (o por teléfono si nos dio un número).",
      "t_step3": "Recibirá una propuesta o un seguimiento personalizado según el tipo de consulta.",
      "t_footer_reply": "¿Preguntas? Responda a este correo o escriba a",
      "t_rights": "Todos los derechos reservados."
    },
    "b2b_retailer_confirm": {
      "t_subject": "Su solicitud de minorista / distribuidor de Sliquid",
      "t_tagline": "Programa de Minoristas y Distribuidores",
      "t_badge": "Solicitud recibida",
      "t_heading": "¡Gracias por su solicitud, {contact_name}!",
      "t_intro_before": "Recibimos la solicitud de",
      "t_intro_after": "para convertirse en minorista o distribuidor de Sliquid. Un miembro de nuestro equipo de ventas revisará su solicitud y se comunicará con usted en breve.",
      "t_label_brands": "Marcas seleccionadas",
      "t_next_heading": "Próximos pasos",
      "t_step1_before": "Nuestro equipo de ventas revisa su solicitud, normalmente en un plazo de",
      "t_step1_duration": "2 a 3 días hábiles",
      "t_step2": "Nos comunicaremos por correo electrónico o por teléfono para hablar de los próximos pasos y responder sus preguntas.",
      "t_step3": "Una vez aprobada, recibirá acceso al Portal de Socios B2B de Sliquid con recursos de pedidos, capacitación y marketing.",
      "t_cta": "Conozca más sobre Sliquid B2B",
      "t_help": "¿Tiene preguntas mientras tanto? Comuníquese con nuestro equipo de ventas en",
      "t_submitted": "Enviado desde",
      "t_rights": "Todos los derechos reservados."
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "Gracias por registrarse, {contact_name} — {reference_number}",
      "t_tagline": "Registro de socios",
      "t_reference": "Referencia",
      "t_heading": "Gracias, {contact_name}.",
      "t_intro_before": "Recibimos el registro de",
      "t_intro_after": "y, más que eso, gracias por el espacio en sus anaqueles. Socios como usted son la razón por la que una marca pequeña y obsesionada con los ingredientes ha llegado a cumplir veinte años.",
      "t_followup": "se comunicará con usted en breve.",
      "t_asked_heading": "Lo que nos solicitó",
      "t_next_heading": "Próximos pasos",
      "t_step1_before": "Su contacto revisa el registro, normalmente en un plazo de",
      "t_step1_duration": "1 a 2 días hábiles",
      "t_step2": "Todo lo que solicitó (materiales de marketing, imágenes de productos, capacitación) se le enviará.",
      "t_step3_before": "Mencione",
      "t_step3_after": "en cualquier respuesta y encontraremos su registro de inmediato.",
      "t_cta": "Abrir el portal de socios",
      "t_help": "¿Necesita algo antes? Escriba a",
      "t_submitted": "Enviado desde",
      "t_rights": "Todos los derechos reservados."
    }
  },
  "roleLabels": {
    "tier1": "Empleado de tienda minorista",
    "tier2": "Gerencia minorista",
    "tier3": "Distribuidor",
    "tier4": "Prospecto",
    "tier5": "Administrador",
    "tier6": "Socio médico",
    "tier7": "Medios",
    "tier8": "Legal (solo lectura)"
  },
  "defaults": {
    "pointOfContact": "Un miembro de nuestro equipo de ventas",
    "interests": "Ninguno seleccionado"
  }
}
