import type { LanguageEmailCopy } from './types.js'

/** French (Canada, "vous") — keys must match en.ts exactly (emailCopy.test.ts). */
export const fr: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "Vous avez réussi {quiz_title} — {score} %",
      "t_tagline": "Portail partenaires B2B",
      "t_badge": "Module terminé",
      "t_heading": "Beau travail, {user_name}!",
      "t_intro_before": "Vous avez réussi le module",
      "t_intro_middle": "avec une note de",
      "t_intro_after": ". Continuez : vous êtes à un pas de devenir Expert certifié Sliquid.",
      "t_label_module": "Module",
      "t_label_score": "Note",
      "t_cta": "Poursuivre la formation →",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_cert_issued": {
      "t_subject": "Votre certificat d’Expert certifié Sliquid",
      "t_tagline": "Portail partenaires B2B",
      "t_heading": "Vous êtes maintenant Expert certifié Sliquid!",
      "t_intro_before": "Félicitations,",
      "t_intro_after": ". Vous avez terminé avec succès l’ensemble du cours de formation Expert certifié Sliquid. Votre certificat a été émis et peut être téléchargé depuis votre portail.",
      "t_label_issued_to": "Délivré à",
      "t_label_completed": "Terminé le",
      "t_label_cert_number": "Numéro de certificat",
      "t_cta": "Voir et télécharger le certificat",
      "t_verify": "Vous pouvez aussi vérifier ce certificat en tout temps à",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_register_confirm": {
      "t_subject": "Votre inscription au portail B2B de Sliquid",
      "t_tagline": "Portail partenaires B2B",
      "t_heading": "Bienvenue, {user_name}!",
      "t_intro_before": "Merci de vous être inscrit au",
      "t_intro_after": ". Nous avons bien reçu votre compte et notre équipe est en train de l’examiner.",
      "t_badge": "En attente d’examen",
      "t_pending": "Notre équipe examinera votre demande et vous donnera accès au portail sous peu. Vous recevrez un courriel de confirmation dès que votre compte sera approuvé.",
      "t_details_heading": "Détails de votre inscription",
      "t_label_name": "Nom",
      "t_label_email": "Courriel",
      "t_help": "Si vous avez des questions d’ici là, n’hésitez pas à nous écrire à",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_approved": {
      "t_subject": "Votre compte du portail B2B de Sliquid est approuvé",
      "t_tagline": "Portail partenaires B2B",
      "t_badge": "Compte approuvé",
      "t_heading": "C’est fait, {user_name}!",
      "t_intro": "Votre compte du portail partenaires B2B de Sliquid a été approuvé. Vous pouvez maintenant vous connecter et accéder à toutes les ressources offertes à votre type de compte.",
      "t_label_role": "Type de compte",
      "t_cta": "Se connecter au portail →",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_declined": {
      "t_subject": "Mise à jour concernant votre demande au portail B2B de Sliquid",
      "t_tagline": "Portail partenaires B2B",
      "t_heading": "Mise à jour concernant votre demande",
      "t_intro": "Bonjour {user_name}, merci de votre intérêt pour le portail partenaires B2B de Sliquid. Après examen de votre demande, nous ne sommes pas en mesure d’approuver l’accès au portail pour le moment.",
      "t_body": "Si vous croyez qu’il s’agit d’une erreur ou souhaitez discuter de votre demande, communiquez avec notre équipe de soutien — nous serons heureux de vous aider.",
      "t_cta": "Joindre le soutien",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_reward_confirm": {
      "t_subject": "Votre récompense Sliquid est en route!",
      "t_tagline": "Portail partenaires B2B",
      "t_badge": "Récompense soumise",
      "t_heading": "Votre récompense est en route, {user_name}!",
      "t_intro": "Nous avons bien reçu votre demande de récompense. Notre équipe traitera la demande et expédiera vos articles à l’adresse inscrite. Surveillez votre boîte de réception pour l’avis d’expédition.",
      "t_label_product": "Produit gratuit",
      "t_label_shirt": "Taille de t-shirt",
      "t_label_ship_to": "Livrer à",
      "t_update_before": "Vous devez modifier votre adresse de livraison? Écrivez à",
      "t_update_after": "dès que possible.",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_marketing_user": {
      "t_subject": "Nous avons bien reçu votre demande de matériel marketing",
      "t_tagline": "Portail partenaires B2B",
      "t_badge": "Demande reçue",
      "t_heading": "Nous avons bien reçu votre demande, {user_name}!",
      "t_intro": "Votre demande marketing a été envoyée. Notre équipe l’examinera et communiquera avec vous pour confirmer les détails.",
      "t_label_items": "Articles demandés",
      "t_help": "Des questions sur votre demande? Écrivez-nous à",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_medical_user": {
      "t_subject": "Nous avons bien reçu votre demande de marketing médical",
      "t_tagline": "Programme pour professionnels de la santé",
      "t_badge": "Demande reçue",
      "t_heading": "Nous avons bien reçu votre demande, {user_name}!",
      "t_intro": "Votre demande de matériel de marketing médical a été envoyée. Notre équipe pour les professionnels de la santé l’examinera et communiquera avec vous pour confirmer l’exécution et les détails de livraison.",
      "t_label_items": "Articles demandés",
      "t_help": "Des questions sur votre demande? Écrivez-nous à",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "portal_password_reset": {
      "t_subject": "Réinitialisez votre mot de passe du portail partenaires Sliquid",
      "t_tagline": "Portail partenaires",
      "t_heading": "Réinitialisez votre mot de passe",
      "t_greeting": "Bonjour {user_name},",
      "t_intro": "Nous avons reçu une demande de réinitialisation du mot de passe de votre compte du portail partenaires Sliquid. Cliquez sur le bouton ci-dessous pour choisir un nouveau mot de passe.",
      "t_cta": "Réinitialiser le mot de passe",
      "t_expiry_before": "Ce lien expire dans",
      "t_expiry_duration": "1 heure",
      "t_expiry_after": ". Si vous ne l’utilisez pas à temps, vous devrez en demander un nouveau.",
      "t_fallback": "Si le bouton ne fonctionne pas, copiez et collez cette adresse dans votre navigateur :",
      "t_ignore": "Si vous n’avez pas demandé de réinitialisation, vous pouvez ignorer ce courriel — votre mot de passe ne changera pas.",
      "t_confidential": "Portail partenaires Sliquid — Confidentiel",
      "t_rights": "Tous droits réservés."
    },
    "portal_asset_broadcast": {
      "t_subject": "Nouveauté dans la bibliothèque de produits Sliquid : {asset_name}",
      "t_tagline": "Portail partenaires B2B",
      "t_badge": "Nouveauté dans la bibliothèque de produits",
      "t_heading": "De nouvelles ressources sont arrivées, {user_name}!",
      "t_intro": "Du nouveau contenu est offert dans votre bibliothèque de produits. Rendez-vous sur le portail pour le consulter et le télécharger pour votre magasin.",
      "t_label_asset": "Ressource",
      "t_label_brand": "Marque",
      "t_cta": "Voir la bibliothèque de produits →",
      "t_footer_sent": "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      "t_footer_questions": "Des questions? Écrivez à"
    },
    "b2b_contact_reply": {
      "t_subject": "Nous avons bien reçu votre message — Sliquid",
      "t_tagline": "Partenariats B2B",
      "t_heading": "Merci de nous avoir écrit, {to_name}!",
      "t_intro_before": "Nous avons bien reçu votre message et un membre de notre équipe B2B l’examinera sous peu. Nous répondons généralement dans un délai de",
      "t_intro_duration": "2 jours ouvrables",
      "t_portal": "D’ici là, vous pouvez explorer notre portail partenaires, qui offre de l’information sur les produits, du matériel marketing et des ressources de formation.",
      "t_cta": "Visiter le portail partenaires",
      "t_next_heading": "Prochaines étapes",
      "t_step1": "Notre équipe examine votre demande et l’achemine à la bonne personne.",
      "t_step2": "Nous communiquerons avec vous par courriel (ou par téléphone si vous avez fourni un numéro).",
      "t_step3": "Vous recevrez une proposition ou un suivi adapté selon le type de demande.",
      "t_footer_reply": "Des questions? Répondez à ce courriel ou écrivez à",
      "t_rights": "Tous droits réservés."
    },
    "b2b_retailer_confirm": {
      "t_subject": "Votre demande de détaillant / distributeur Sliquid",
      "t_tagline": "Programme des détaillants et distributeurs",
      "t_badge": "Demande reçue",
      "t_heading": "Merci pour votre demande, {contact_name}!",
      "t_intro_before": "Nous avons bien reçu la demande de",
      "t_intro_after": "pour devenir détaillant ou distributeur Sliquid. Un membre de notre équipe des ventes examinera votre demande et communiquera avec vous sous peu.",
      "t_label_brands": "Marques sélectionnées",
      "t_next_heading": "Prochaines étapes",
      "t_step1_before": "Notre équipe des ventes examine votre demande — généralement dans un délai de",
      "t_step1_duration": "2 à 3 jours ouvrables",
      "t_step2": "Nous communiquerons avec vous par courriel ou par téléphone pour discuter des prochaines étapes et répondre à vos questions.",
      "t_step3": "Une fois la demande approuvée, vous aurez accès au portail partenaires B2B de Sliquid et à ses ressources de commande, de formation et de marketing.",
      "t_cta": "En savoir plus sur Sliquid B2B",
      "t_help": "Des questions d’ici là? Communiquez avec notre équipe des ventes à",
      "t_submitted": "Soumis via",
      "t_rights": "Tous droits réservés."
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "Merci pour votre suivi, {contact_name} — {reference_number}",
      "t_tagline": "Suivi des partenaires",
      "t_reference": "Référence",
      "t_heading": "Merci, {contact_name}.",
      "t_intro_before": "Nous avons bien reçu le suivi de",
      "t_intro_after": "— et surtout, merci pour l’espace sur vos tablettes. Ce sont des partenaires comme vous qui ont permis à une petite marque obsédée par les ingrédients de durer vingt ans.",
      "t_followup": "communiquera avec vous sous peu.",
      "t_asked_heading": "Ce que vous nous avez demandé",
      "t_next_heading": "Prochaines étapes",
      "t_step1_before": "Votre personne-ressource examine le suivi — généralement dans un délai de",
      "t_step1_duration": "1 à 2 jours ouvrables",
      "t_step2": "Tout ce que vous avez demandé — matériel marketing, images de produits, formation — vous sera envoyé.",
      "t_step3_before": "Indiquez",
      "t_step3_after": "dans toute réponse et nous retrouverons votre suivi immédiatement.",
      "t_cta": "Ouvrir le portail partenaires",
      "t_help": "Besoin de quelque chose plus tôt? Écrivez à",
      "t_submitted": "Soumis via",
      "t_rights": "Tous droits réservés."
    }
  },
  "roleLabels": {
    "tier1": "Employé de magasin",
    "tier2": "Direction de magasin",
    "tier3": "Distributeur",
    "tier4": "Prospect",
    "tier5": "Administrateur",
    "tier6": "Partenaire médical",
    "tier7": "Médias",
    "tier8": "Juridique (lecture seule)"
  },
  "defaults": {
    "pointOfContact": "Un membre de notre équipe des ventes",
    "interests": "Aucune sélection"
  }
}
