import type { LanguageEmailCopy } from './types.js'

/** Dutch (formal "u") — keys must match en.ts exactly (emailCopy.test.ts). */
export const nl: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "U bent geslaagd voor {quiz_title} — {score}%",
      "t_tagline": "B2B-partnerportaal",
      "t_badge": "Module voltooid",
      "t_heading": "Goed gedaan, {user_name}!",
      "t_intro_before": "U bent geslaagd voor de module",
      "t_intro_middle": "met een score van",
      "t_intro_after": ". Ga zo door — u bent weer een stap dichter bij Sliquid Certified Expert.",
      "t_label_module": "Module",
      "t_label_score": "Score",
      "t_cta": "Verder met de training →",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_cert_issued": {
      "t_subject": "Uw Sliquid Certified Expert-certificaat",
      "t_tagline": "B2B-partnerportaal",
      "t_heading": "U bent een Sliquid Certified Expert!",
      "t_intro_before": "Gefeliciteerd,",
      "t_intro_after": ". U heeft de volledige Sliquid Certified Expert-training met succes afgerond. Uw certificaat is uitgegeven en staat klaar om te downloaden in uw portaal.",
      "t_label_issued_to": "Uitgegeven aan",
      "t_label_completed": "Voltooid",
      "t_label_cert_number": "Certificaatnummer",
      "t_cta": "Certificaat bekijken en downloaden",
      "t_verify": "U kunt dit certificaat ook altijd verifiëren op",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_register_confirm": {
      "t_subject": "Uw registratie voor het Sliquid B2B-portaal",
      "t_tagline": "B2B-partnerportaal",
      "t_heading": "Welkom, {user_name}!",
      "t_intro_before": "Bedankt voor uw registratie bij het",
      "t_intro_after": ". Uw account is ontvangen en wordt momenteel beoordeeld door ons team.",
      "t_badge": "In behandeling",
      "t_pending": "Ons team beoordeelt uw aanvraag en geeft u binnenkort toegang tot het portaal. U ontvangt een bevestigingsmail zodra uw account is goedgekeurd.",
      "t_details_heading": "Uw registratiegegevens",
      "t_label_name": "Naam",
      "t_label_email": "E-mail",
      "t_help": "Heeft u in de tussentijd vragen? Neem gerust contact op via",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_approved": {
      "t_subject": "Uw account voor het Sliquid B2B-portaal is goedgekeurd",
      "t_tagline": "B2B-partnerportaal",
      "t_badge": "Account goedgekeurd",
      "t_heading": "U bent binnen, {user_name}!",
      "t_intro": "Uw account voor het Sliquid B2B-partnerportaal is goedgekeurd. U kunt nu inloggen en alle middelen gebruiken die bij uw accounttype horen.",
      "t_label_role": "Accounttype",
      "t_cta": "Inloggen op uw portaal →",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_declined": {
      "t_subject": "Een update over uw aanvraag voor het Sliquid B2B-portaal",
      "t_tagline": "B2B-partnerportaal",
      "t_heading": "Een update over uw aanvraag",
      "t_intro": "Beste {user_name}, bedankt voor uw interesse in het Sliquid B2B-partnerportaal. Na beoordeling van uw aanvraag kunnen wij op dit moment helaas geen toegang tot het portaal verlenen.",
      "t_body": "Denkt u dat dit een vergissing is of wilt u uw aanvraag bespreken? Neem dan contact op met ons supportteam — wij helpen u graag.",
      "t_cta": "Contact opnemen met support",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_reward_confirm": {
      "t_subject": "Uw Sliquid-beloning is onderweg!",
      "t_tagline": "B2B-partnerportaal",
      "t_badge": "Beloning aangevraagd",
      "t_heading": "Uw beloning is onderweg, {user_name}!",
      "t_intro": "We hebben uw aanvraag voor de beloning ontvangen. Ons team verwerkt uw artikelen en verzendt ze naar het bekende adres. Houd uw inbox in de gaten voor een verzendbevestiging.",
      "t_label_product": "Gratis product",
      "t_label_shirt": "T-shirtmaat",
      "t_label_ship_to": "Verzenden naar",
      "t_update_before": "Moet uw verzendadres worden aangepast? Neem zo snel mogelijk contact op met",
      "t_update_after": ".",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_marketing_user": {
      "t_subject": "Uw aanvraag voor marketingmateriaal is ontvangen",
      "t_tagline": "B2B-partnerportaal",
      "t_badge": "Aanvraag ontvangen",
      "t_heading": "We hebben uw aanvraag ontvangen, {user_name}!",
      "t_intro": "Uw marketingaanvraag is ingediend. Ons team beoordeelt deze en neemt contact met u op om de details te bevestigen.",
      "t_label_items": "Aangevraagde artikelen",
      "t_help": "Vragen over uw aanvraag? Neem contact op via",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_medical_user": {
      "t_subject": "Uw aanvraag voor medisch marketingmateriaal is ontvangen",
      "t_tagline": "Programma voor zorgverleners",
      "t_badge": "Aanvraag ontvangen",
      "t_heading": "We hebben uw aanvraag ontvangen, {user_name}!",
      "t_intro": "Uw aanvraag voor medisch marketingmateriaal is ingediend. Ons team voor zorgverleners beoordeelt deze en neemt contact met u op om de levering en verzendgegevens te bevestigen.",
      "t_label_items": "Aangevraagde artikelen",
      "t_help": "Vragen over uw aanvraag? Neem contact op via",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "portal_password_reset": {
      "t_subject": "Herstel uw wachtwoord voor het Sliquid Partnerportaal",
      "t_tagline": "Partnerportaal",
      "t_heading": "Herstel uw wachtwoord",
      "t_greeting": "Beste {user_name},",
      "t_intro": "We hebben een verzoek ontvangen om het wachtwoord van uw account voor het Sliquid Partnerportaal te herstellen. Klik op de knop hieronder om een nieuw wachtwoord te kiezen.",
      "t_cta": "Wachtwoord herstellen",
      "t_expiry_before": "Deze link verloopt over",
      "t_expiry_duration": "1 uur",
      "t_expiry_after": ". Gebruikt u hem niet op tijd, dan moet u een nieuwe aanvragen.",
      "t_fallback": "Werkt de knop hierboven niet? Kopieer deze URL en plak hem in uw browser:",
      "t_ignore": "Heeft u geen wachtwoordherstel aangevraagd? Dan kunt u deze e-mail veilig negeren — uw wachtwoord blijft ongewijzigd.",
      "t_confidential": "Sliquid Partnerportaal — vertrouwelijk",
      "t_rights": "Alle rechten voorbehouden."
    },
    "portal_asset_broadcast": {
      "t_subject": "Nieuw in de Sliquid-productbibliotheek: {asset_name}",
      "t_tagline": "B2B-partnerportaal",
      "t_badge": "Nieuw in de productbibliotheek",
      "t_heading": "Er zijn nieuwe bestanden, {user_name}!",
      "t_intro": "Er staat nieuwe content klaar in uw productbibliotheek. Ga naar het portaal om deze te bekijken en te downloaden voor uw winkel.",
      "t_label_asset": "Bestand",
      "t_label_brand": "Merk",
      "t_cta": "Productbibliotheek bekijken →",
      "t_footer_sent": "Deze e-mail is verzonden door het Sliquid B2B-partnerportaal.",
      "t_footer_questions": "Vragen? Neem contact op met"
    },
    "b2b_contact_reply": {
      "t_subject": "We hebben uw bericht ontvangen — Sliquid",
      "t_tagline": "B2B-partnerschappen",
      "t_heading": "Bedankt voor uw bericht, {to_name}!",
      "t_intro_before": "We hebben uw bericht ontvangen en een medewerker van ons B2B-team bekijkt het binnenkort. Wij reageren doorgaans binnen",
      "t_intro_duration": "2 werkdagen",
      "t_portal": "In de tussentijd kunt u gerust ons partnerportaal verkennen, met productinformatie, marketingmateriaal en trainingsmateriaal.",
      "t_cta": "Naar het partnerportaal",
      "t_next_heading": "Wat er daarna gebeurt",
      "t_step1": "Ons team beoordeelt uw vraag en koppelt deze aan de juiste contactpersoon.",
      "t_step2": "Wij nemen per e-mail contact op (of telefonisch, als u een nummer heeft opgegeven).",
      "t_step3": "U ontvangt een voorstel op maat of een vervolg op basis van het type vraag.",
      "t_footer_reply": "Vragen? Beantwoord deze e-mail of neem contact op met",
      "t_rights": "Alle rechten voorbehouden."
    },
    "b2b_retailer_confirm": {
      "t_subject": "Uw aanvraag als Sliquid-detailhandelaar / -distributeur",
      "t_tagline": "Programma voor detailhandel en distributie",
      "t_badge": "Aanvraag ontvangen",
      "t_heading": "Bedankt voor uw aanvraag, {contact_name}!",
      "t_intro_before": "We hebben uw aanvraag ontvangen voor",
      "t_intro_after": "om Sliquid-detailhandelaar of -distributeur te worden. Een medewerker van ons verkoopteam beoordeelt uw inzending en neemt binnenkort contact met u op.",
      "t_label_brands": "Door u gekozen merken",
      "t_next_heading": "Wat er daarna gebeurt",
      "t_step1_before": "Ons verkoopteam beoordeelt uw aanvraag — doorgaans binnen",
      "t_step1_duration": "2–3 werkdagen",
      "t_step2": "Wij nemen per e-mail of telefoon contact op om de vervolgstappen te bespreken en uw vragen te beantwoorden.",
      "t_step3": "Na goedkeuring krijgt u toegang tot het Sliquid B2B-partnerportaal met bestellen, trainingen en marketingmateriaal.",
      "t_cta": "Meer over Sliquid B2B",
      "t_help": "Heeft u in de tussentijd vragen? Neem contact op met ons verkoopteam via",
      "t_submitted": "Verzonden via",
      "t_rights": "Alle rechten voorbehouden."
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "Bedankt voor uw check-in, {contact_name} — {reference_number}",
      "t_tagline": "Check-in voor partners",
      "t_reference": "Referentie",
      "t_heading": "Bedankt, {contact_name}.",
      "t_intro_before": "We hebben uw check-in ontvangen voor",
      "t_intro_after": "— en vooral: bedankt voor de schapruimte. Dankzij partners zoals u kon een klein merk dat geobsedeerd is door ingrediënten al twintig jaar bestaan.",
      "t_followup": "neemt binnenkort contact met u op.",
      "t_asked_heading": "Waar u om heeft gevraagd",
      "t_next_heading": "Wat er daarna gebeurt",
      "t_step1_before": "Uw contactpersoon bekijkt de check-in — meestal binnen",
      "t_step1_duration": "1–2 werkdagen",
      "t_step2": "Alles waar u om heeft gevraagd — marketingmateriaal, productafbeeldingen, training — wordt naar u verzonden.",
      "t_step3_before": "Vermeld",
      "t_step3_after": "in elk antwoord, dan hebben we uw check-in direct bij de hand.",
      "t_cta": "Het partnerportaal openen",
      "t_help": "Heeft u iets eerder nodig? Mail naar",
      "t_submitted": "Verzonden via",
      "t_rights": "Alle rechten voorbehouden."
    }
  },
  "roleLabels": {
    "tier1": "Winkelmedewerker",
    "tier2": "Winkelmanagement",
    "tier3": "Distributeur",
    "tier4": "Prospect",
    "tier5": "Beheerder",
    "tier6": "Medische partner",
    "tier7": "Media",
    "tier8": "Juridisch (alleen lezen)"
  },
  "defaults": {
    "pointOfContact": "Een medewerker van ons verkoopteam",
    "interests": "Niets geselecteerd"
  }
}
