import type { LanguageEmailCopy } from './types.js'

/** Brazilian Portuguese ("você") — keys must match en.ts exactly (emailCopy.test.ts). */
export const pt: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "Você foi aprovado em {quiz_title} — {score}%",
      "t_tagline": "Portal de Parceiros B2B",
      "t_badge": "Módulo concluído",
      "t_heading": "Ótimo trabalho, {user_name}!",
      "t_intro_before": "Você foi aprovado no módulo",
      "t_intro_middle": "com a pontuação de",
      "t_intro_after": ". Continue assim — você está um passo mais perto de se tornar um Sliquid Certified Expert.",
      "t_label_module": "Módulo",
      "t_label_score": "Pontuação",
      "t_cta": "Continuar o treinamento →",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_cert_issued": {
      "t_subject": "Seu certificado Sliquid Certified Expert",
      "t_tagline": "Portal de Parceiros B2B",
      "t_heading": "Você é um Sliquid Certified Expert!",
      "t_intro_before": "Parabéns,",
      "t_intro_after": ". Você concluiu com sucesso todo o Sliquid Certified Expert Training Course. Seu certificado foi emitido e está pronto para download no seu portal.",
      "t_label_issued_to": "Emitido para",
      "t_label_completed": "Concluído em",
      "t_label_cert_number": "Número do certificado",
      "t_cta": "Ver e baixar o certificado",
      "t_verify": "Você também pode verificar este certificado a qualquer momento em",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_register_confirm": {
      "t_subject": "Seu cadastro no Portal B2B da Sliquid",
      "t_tagline": "Portal de Parceiros B2B",
      "t_heading": "Boas-vindas, {user_name}!",
      "t_intro_before": "Obrigado por se cadastrar no",
      "t_intro_after": ". Recebemos seu cadastro e ele está em análise pela nossa equipe.",
      "t_badge": "Em análise",
      "t_pending": "Nossa equipe analisará sua solicitação e liberará o acesso ao portal em breve. Você receberá um e-mail de confirmação assim que sua conta for aprovada.",
      "t_details_heading": "Dados do seu cadastro",
      "t_label_name": "Nome",
      "t_label_email": "E-mail",
      "t_help": "Se tiver alguma dúvida enquanto isso, fale conosco pelo",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_approved": {
      "t_subject": "Sua conta no Portal B2B da Sliquid foi aprovada",
      "t_tagline": "Portal de Parceiros B2B",
      "t_badge": "Conta aprovada",
      "t_heading": "Tudo pronto, {user_name}!",
      "t_intro": "Sua conta no Portal de Parceiros B2B da Sliquid foi aprovada. Agora você pode entrar e acessar todos os recursos disponíveis para o seu tipo de conta.",
      "t_label_role": "Tipo de conta",
      "t_cta": "Entrar no seu portal →",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_declined": {
      "t_subject": "Uma atualização sobre sua solicitação ao Portal B2B da Sliquid",
      "t_tagline": "Portal de Parceiros B2B",
      "t_heading": "Uma atualização sobre sua solicitação",
      "t_intro": "Olá, {user_name}. Obrigado pelo seu interesse no Portal de Parceiros B2B da Sliquid. Após analisar sua solicitação, não podemos aprovar o acesso ao portal neste momento.",
      "t_body": "Se você acredita que houve um erro ou gostaria de conversar sobre sua solicitação, entre em contato com nossa equipe de suporte — teremos prazer em ajudar.",
      "t_cta": "Falar com o suporte",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_reward_confirm": {
      "t_subject": "Sua recompensa Sliquid está a caminho!",
      "t_tagline": "Portal de Parceiros B2B",
      "t_badge": "Recompensa solicitada",
      "t_heading": "Sua recompensa está a caminho, {user_name}!",
      "t_intro": "Recebemos seu pedido de recompensa. Nossa equipe vai processar e enviar seus itens para o endereço cadastrado. Fique de olho na sua caixa de entrada para o aviso de envio.",
      "t_label_product": "Produto grátis",
      "t_label_shirt": "Tamanho da camiseta",
      "t_label_ship_to": "Enviar para",
      "t_update_before": "Precisa atualizar seu endereço de entrega? Fale com",
      "t_update_after": "o quanto antes.",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_marketing_user": {
      "t_subject": "Recebemos sua solicitação de materiais de marketing",
      "t_tagline": "Portal de Parceiros B2B",
      "t_badge": "Solicitação recebida",
      "t_heading": "Recebemos sua solicitação, {user_name}!",
      "t_intro": "Sua solicitação de marketing foi enviada. Nossa equipe vai analisá-la e entrar em contato para confirmar os detalhes.",
      "t_label_items": "Itens solicitados",
      "t_help": "Dúvidas sobre sua solicitação? Fale conosco pelo",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_medical_user": {
      "t_subject": "Recebemos sua solicitação de marketing médico",
      "t_tagline": "Programa para Profissionais de Saúde",
      "t_badge": "Solicitação recebida",
      "t_heading": "Recebemos sua solicitação, {user_name}!",
      "t_intro": "Sua solicitação de materiais de marketing médico foi enviada. Nossa equipe de profissionais de saúde vai analisá-la e entrar em contato para confirmar o atendimento e os detalhes de envio.",
      "t_label_items": "Itens solicitados",
      "t_help": "Dúvidas sobre sua solicitação? Fale conosco pelo",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "portal_password_reset": {
      "t_subject": "Redefina sua senha do Portal de Parceiros Sliquid",
      "t_tagline": "Portal de Parceiros",
      "t_heading": "Redefina sua senha",
      "t_greeting": "Olá, {user_name},",
      "t_intro": "Recebemos uma solicitação para redefinir a senha da sua conta no Portal de Parceiros Sliquid. Clique no botão abaixo para escolher uma nova senha.",
      "t_cta": "Redefinir senha",
      "t_expiry_before": "Este link expira em",
      "t_expiry_duration": "1 hora",
      "t_expiry_after": ". Se você não usá-lo a tempo, precisará solicitar um novo.",
      "t_fallback": "Se o botão acima não funcionar, copie e cole este endereço no seu navegador:",
      "t_ignore": "Se você não solicitou a redefinição de senha, pode ignorar este e-mail com segurança — sua senha não será alterada.",
      "t_confidential": "Portal de Parceiros Sliquid — Confidencial",
      "t_rights": "Todos os direitos reservados."
    },
    "portal_asset_broadcast": {
      "t_subject": "Novidade na Biblioteca de produtos Sliquid: {asset_name}",
      "t_tagline": "Portal de Parceiros B2B",
      "t_badge": "Novidade na Biblioteca de produtos",
      "t_heading": "Acabaram de chegar novos materiais, {user_name}!",
      "t_intro": "Há conteúdo novo disponível na sua Biblioteca de produtos. Acesse o portal para visualizar e baixar o material para a sua loja.",
      "t_label_asset": "Material",
      "t_label_brand": "Marca",
      "t_cta": "Ver a Biblioteca de produtos →",
      "t_footer_sent": "Este e-mail foi enviado pelo Portal de Parceiros B2B da Sliquid.",
      "t_footer_questions": "Dúvidas? Fale com"
    },
    "b2b_contact_reply": {
      "t_subject": "Recebemos sua mensagem — Sliquid",
      "t_tagline": "Parcerias B2B",
      "t_heading": "Obrigado pelo contato, {to_name}!",
      "t_intro_before": "Recebemos sua mensagem e um membro da nossa equipe B2B vai analisá-la em breve. Normalmente respondemos em até",
      "t_intro_duration": "2 dias úteis",
      "t_portal": "Enquanto isso, fique à vontade para conhecer nosso portal de parceiros, onde você encontra informações de produtos, materiais de marketing e recursos de treinamento.",
      "t_cta": "Acessar o Portal de parceiros",
      "t_next_heading": "Próximos passos",
      "t_step1": "Nossa equipe analisa seu contato e o direciona à pessoa certa.",
      "t_step2": "Entraremos em contato por e-mail (ou telefone, se você informou um número).",
      "t_step3": "Você receberá uma proposta personalizada ou um retorno de acordo com o tipo de contato.",
      "t_footer_reply": "Dúvidas? Responda a este e-mail ou fale com",
      "t_rights": "Todos os direitos reservados."
    },
    "b2b_retailer_confirm": {
      "t_subject": "Sua candidatura para varejista / distribuidor Sliquid",
      "t_tagline": "Programa de Varejistas e Distribuidores",
      "t_badge": "Candidatura recebida",
      "t_heading": "Obrigado pela candidatura, {contact_name}!",
      "t_intro_before": "Recebemos a candidatura de",
      "t_intro_after": "para se tornar varejista ou distribuidor Sliquid. Um membro da nossa equipe de vendas vai analisar seu envio e entrar em contato em breve.",
      "t_label_brands": "Marcas selecionadas",
      "t_next_heading": "Próximos passos",
      "t_step1_before": "Nossa equipe de vendas analisa sua candidatura — normalmente em até",
      "t_step1_duration": "2 a 3 dias úteis",
      "t_step2": "Entraremos em contato por e-mail ou telefone para conversar sobre os próximos passos e tirar suas dúvidas.",
      "t_step3": "Após a aprovação, você terá acesso ao Portal de Parceiros B2B da Sliquid, com pedidos, treinamentos e recursos de marketing.",
      "t_cta": "Saiba mais sobre a Sliquid B2B",
      "t_help": "Tem alguma dúvida enquanto isso? Fale com nossa equipe de vendas pelo",
      "t_submitted": "Enviado via",
      "t_rights": "Todos os direitos reservados."
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "Obrigado pelo contato, {contact_name} — {reference_number}",
      "t_tagline": "Contato de parceiros",
      "t_reference": "Referência",
      "t_heading": "Obrigado, {contact_name}.",
      "t_intro_before": "Recebemos o contato de",
      "t_intro_after": "— e, mais do que isso, obrigado pelo espaço na prateleira. Parceiros como você são o motivo pelo qual uma marca pequena e obcecada por ingredientes chegou a vinte anos de história.",
      "t_followup": "entrará em contato com você em breve.",
      "t_asked_heading": "O que você nos pediu",
      "t_next_heading": "Próximos passos",
      "t_step1_before": "Seu contato analisa a mensagem — geralmente em até",
      "t_step1_duration": "1 a 2 dias úteis",
      "t_step2": "Tudo o que você pediu — materiais de marketing, imagens de produtos, treinamento — será enviado para você.",
      "t_step3_before": "Informe",
      "t_step3_after": "em qualquer resposta e localizaremos seu contato na hora.",
      "t_cta": "Abrir o Portal de parceiros",
      "t_help": "Precisa de algo antes? Envie um e-mail para",
      "t_submitted": "Enviado via",
      "t_rights": "Todos os direitos reservados."
    }
  },
  "roleLabels": {
    "tier1": "Funcionário de loja",
    "tier2": "Gerência de loja",
    "tier3": "Distribuidor",
    "tier4": "Prospect",
    "tier5": "Administrador",
    "tier6": "Parceiro médico",
    "tier7": "Mídia",
    "tier8": "Jurídico (somente leitura)"
  },
  "defaults": {
    "pointOfContact": "Um membro da nossa equipe de vendas",
    "interests": "Nenhum selecionado"
  }
}
