import type { LanguageEmailCopy } from './types.js'

/** Simplified Chinese — keys must match en.ts exactly (emailCopy.test.ts). */
export const zh: LanguageEmailCopy = {
  "templates": {
    "portal_quiz_pass": {
      "t_subject": "您已通过 {quiz_title}——得分 {score}%",
      "t_tagline": "B2B 合作伙伴门户",
      "t_badge": "模块已完成",
      "t_heading": "做得好，{user_name}！",
      "t_intro_before": "您已通过",
      "t_intro_middle": "模块，得分为",
      "t_intro_after": "。继续加油——您离成为 Sliquid 认证专家又近了一步。",
      "t_label_module": "模块",
      "t_label_score": "得分",
      "t_cta": "继续培训 →",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_cert_issued": {
      "t_subject": "您的 Sliquid 认证专家证书",
      "t_tagline": "B2B 合作伙伴门户",
      "t_heading": "您已成为 Sliquid 认证专家！",
      "t_intro_before": "恭喜您，",
      "t_intro_after": "！您已成功完成整个 Sliquid 认证专家培训课程。您的证书已颁发，可在您的门户中下载。",
      "t_label_issued_to": "颁发给",
      "t_label_completed": "完成日期",
      "t_label_cert_number": "证书编号",
      "t_cta": "查看并下载证书",
      "t_verify": "您也可以随时通过以下网址验证此证书：",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_register_confirm": {
      "t_subject": "您的 Sliquid B2B 门户注册信息",
      "t_tagline": "B2B 合作伙伴门户",
      "t_heading": "欢迎您，{user_name}！",
      "t_intro_before": "感谢您注册",
      "t_intro_after": "。我们已收到您的账户信息，目前正在由我们的团队审核。",
      "t_badge": "待审核",
      "t_pending": "我们的团队将审核您的申请，并尽快为您开通门户访问权限。账户获批后，您将收到一封确认邮件。",
      "t_details_heading": "您的注册信息",
      "t_label_name": "姓名",
      "t_label_email": "电子邮件",
      "t_help": "在此期间如有任何问题，欢迎随时联系",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_approved": {
      "t_subject": "您的 Sliquid B2B 门户账户已获批准",
      "t_tagline": "B2B 合作伙伴门户",
      "t_badge": "账户已获批准",
      "t_heading": "欢迎加入，{user_name}！",
      "t_intro": "您的 Sliquid B2B 合作伙伴门户账户已获批准。您现在可以登录，并访问您的账户类型可用的所有资源。",
      "t_label_role": "账户类型",
      "t_cta": "登录您的门户 →",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_declined": {
      "t_subject": "关于您的 Sliquid B2B 门户申请的最新进展",
      "t_tagline": "B2B 合作伙伴门户",
      "t_heading": "关于您的申请的最新进展",
      "t_intro": "{user_name}，您好！感谢您对 Sliquid B2B 合作伙伴门户的关注。经过审核，我们目前无法批准您的门户访问申请。",
      "t_body": "如果您认为这是误判，或希望进一步沟通您的申请，请联系我们的支持团队——我们很乐意为您提供帮助。",
      "t_cta": "联系支持团队",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_reward_confirm": {
      "t_subject": "您的 Sliquid 奖励正在寄送途中！",
      "t_tagline": "B2B 合作伙伴门户",
      "t_badge": "奖励已提交",
      "t_heading": "{user_name}，您的奖励正在寄送途中！",
      "t_intro": "我们已收到您的奖励申领。我们的团队将处理并把物品寄送至您登记的地址。请留意收件箱中的发货通知。",
      "t_label_product": "免费产品",
      "t_label_shirt": "T 恤尺码",
      "t_label_ship_to": "收货地址",
      "t_update_before": "需要更新收货地址？请尽快联系",
      "t_update_after": "。",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_marketing_user": {
      "t_subject": "我们已收到您的营销物料申请",
      "t_tagline": "B2B 合作伙伴门户",
      "t_badge": "已收到申请",
      "t_heading": "{user_name}，我们已收到您的申请！",
      "t_intro": "您的营销申请已提交。我们的团队将进行审核，并与您联系确认详情。",
      "t_label_items": "所申请的物品",
      "t_help": "对您的申请有疑问？请联系",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_medical_user": {
      "t_subject": "我们已收到您的医疗营销物料申请",
      "t_tagline": "医疗从业者计划",
      "t_badge": "已收到申请",
      "t_heading": "{user_name}，我们已收到您的申请！",
      "t_intro": "您的医疗营销物料申请已提交。我们的医疗从业者团队将进行审核，并与您联系确认交付和寄送详情。",
      "t_label_items": "所申请的物品",
      "t_help": "对您的申请有疑问？请联系",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "portal_password_reset": {
      "t_subject": "重置您的 Sliquid 合作伙伴门户密码",
      "t_tagline": "合作伙伴门户",
      "t_heading": "重置您的密码",
      "t_greeting": "{user_name}，您好：",
      "t_intro": "我们收到了重置您 Sliquid 合作伙伴门户账户密码的请求。请点击下方按钮设置新密码。",
      "t_cta": "重置密码",
      "t_expiry_before": "此链接将在",
      "t_expiry_duration": "1 小时",
      "t_expiry_after": "后失效。如果您未能及时使用，则需要重新申请。",
      "t_fallback": "如果上方按钮无法使用，请将以下网址复制并粘贴到浏览器中：",
      "t_ignore": "如果您并未申请重置密码，可以放心忽略此邮件——您的密码不会更改。",
      "t_confidential": "Sliquid 合作伙伴门户——机密",
      "t_rights": "保留所有权利。"
    },
    "portal_asset_broadcast": {
      "t_subject": "Sliquid 产品库新增内容：{asset_name}",
      "t_tagline": "B2B 合作伙伴门户",
      "t_badge": "产品库新增内容",
      "t_heading": "{user_name}，新资源已上线！",
      "t_intro": "您的产品库中已有新内容。请前往门户预览并下载，用于您的门店。",
      "t_label_asset": "资源",
      "t_label_brand": "品牌",
      "t_cta": "查看产品库 →",
      "t_footer_sent": "此邮件由 Sliquid B2B 合作伙伴门户发送。",
      "t_footer_questions": "有疑问？请联系"
    },
    "b2b_contact_reply": {
      "t_subject": "我们已收到您的留言——Sliquid",
      "t_tagline": "B2B 合作",
      "t_heading": "{to_name}，感谢您与我们联系！",
      "t_intro_before": "我们已收到您的留言，B2B 团队成员将很快进行审核。我们通常会在以下时间内回复：",
      "t_intro_duration": "2 个工作日",
      "t_portal": "在此期间，欢迎您浏览我们的合作伙伴门户，获取产品信息、营销资源和培训资料。",
      "t_cta": "访问合作伙伴门户",
      "t_next_heading": "后续流程",
      "t_step1": "我们的团队会审核您的咨询，并将其转交给合适的联系人。",
      "t_step2": "我们将通过电子邮件（如您提供了号码，也可能致电）与您联系。",
      "t_step3": "您将根据咨询类型收到定制方案或后续跟进。",
      "t_footer_reply": "有疑问？请回复此邮件或联系",
      "t_rights": "保留所有权利。"
    },
    "b2b_retailer_confirm": {
      "t_subject": "您的 Sliquid 零售商 / 经销商申请",
      "t_tagline": "零售商与经销商计划",
      "t_badge": "已收到申请",
      "t_heading": "{contact_name}，感谢您的申请！",
      "t_intro_before": "我们已收到",
      "t_intro_after": "成为 Sliquid 零售商或经销商的申请。我们的销售团队成员将审核您的申请，并很快与您联系。",
      "t_label_brands": "您选择的品牌",
      "t_next_heading": "后续流程",
      "t_step1_before": "我们的销售团队将审核您的申请——通常需要",
      "t_step1_duration": "2–3 个工作日",
      "t_step2": "我们将通过电子邮件或电话与您联系，讨论后续步骤并解答您的疑问。",
      "t_step3": "获批后，您将获得 Sliquid B2B 合作伙伴门户的访问权限，可使用订购、培训和营销资源。",
      "t_cta": "进一步了解 Sliquid B2B",
      "t_help": "在此期间有任何疑问？请联系我们的销售团队：",
      "t_submitted": "提交自",
      "t_rights": "保留所有权利。"
    },
    "b2b_retailer_checkin_confirm": {
      "t_subject": "{contact_name}，感谢您的回访——{reference_number}",
      "t_tagline": "合作伙伴回访",
      "t_reference": "参考编号",
      "t_heading": "谢谢您，{contact_name}。",
      "t_intro_before": "我们已收到",
      "t_intro_after": "的回访信息——更重要的是，感谢您提供的货架空间。正是像您这样的合作伙伴，让一个专注于成分的小品牌走过了二十年。",
      "t_followup": "将很快与您跟进。",
      "t_asked_heading": "您向我们提出的需求",
      "t_next_heading": "后续流程",
      "t_step1_before": "您的联系人将审核回访信息——通常需要",
      "t_step1_duration": "1–2 个工作日",
      "t_step2": "您所需的任何内容——营销物料、产品图片、培训——都会寄送给您。",
      "t_step3_before": "在任何回复中注明",
      "t_step3_after": "，我们即可直接调出您的回访信息。",
      "t_cta": "打开合作伙伴门户",
      "t_help": "需要更快处理？请发送电子邮件至",
      "t_submitted": "提交自",
      "t_rights": "保留所有权利。"
    }
  },
  "roleLabels": {
    "tier1": "零售门店员工",
    "tier2": "零售管理人员",
    "tier3": "经销商",
    "tier4": "潜在客户",
    "tier5": "管理员",
    "tier6": "医疗合作伙伴",
    "tier7": "媒体",
    "tier8": "法务（只读）"
  },
  "defaults": {
    "pointOfContact": "我们销售团队的一名成员",
    "interests": "未选择"
  }
}
