/**
 * Translated copy for partner-facing emails (Phase 5).
 *
 * GENERATED once from the EmailJS templates in portal/email-templates/ — the
 * English strings are the templates' original wording, verbatim. Edit here
 * from now on; `emailCopy.test.ts` fails if a template references a t_* key
 * this file lacks (or vice versa), or if a language is missing a key.
 *
 * Each template gets `lang` plus `t_*` variables (see emailVars()). Dynamic
 * values use `{name}` placeholders, filled server-side and then HTML-escaped by
 * EmailJS's `{{t_*}}` — never render these with triple braces.
 *
 * Admin-facing templates (*_admin, portal_register_admin, b2b_hp_application)
 * are deliberately absent: they go to the Sliquid team and stay English.
 */
import type { Language } from './languages.js'

type Copy = Record<string, string>

export const EMAIL_COPY = {
  portal_quiz_pass: {
    en: {
      t_subject: "You passed {quiz_title} — {score}%",
      t_tagline: "B2B Partner Portal",
      t_badge: "Module Complete",
      t_heading: "Nice work, {user_name}!",
      t_intro_before: "You passed the",
      t_intro_middle: "module with a score of",
      t_intro_after: ". Keep going — you're one step closer to becoming a Sliquid Certified Expert.",
      t_label_module: "Module",
      t_label_score: "Score",
      t_cta: "Continue Training →",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Aprobó {quiz_title}: {score}%",
      t_tagline: "Portal de Socios B2B",
      t_badge: "Módulo completado",
      t_heading: "¡Buen trabajo, {user_name}!",
      t_intro_before: "Aprobó el módulo",
      t_intro_middle: "con una puntuación de",
      t_intro_after: ". Siga así: está un paso más cerca de convertirse en Experto Certificado Sliquid.",
      t_label_module: "Módulo",
      t_label_score: "Puntuación",
      t_cta: "Continuar la capacitación →",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Vous avez réussi {quiz_title} — {score} %",
      t_tagline: "Portail partenaires B2B",
      t_badge: "Module terminé",
      t_heading: "Beau travail, {user_name}!",
      t_intro_before: "Vous avez réussi le module",
      t_intro_middle: "avec une note de",
      t_intro_after: ". Continuez : vous êtes à un pas de devenir Expert certifié Sliquid.",
      t_label_module: "Module",
      t_label_score: "Note",
      t_cta: "Poursuivre la formation →",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_cert_issued: {
    en: {
      t_subject: "Your Sliquid Certified Expert Certificate",
      t_tagline: "B2B Partner Portal",
      t_heading: "You're a Sliquid Certified Expert!",
      t_intro_before: "Congratulations,",
      t_intro_after: ". You've successfully completed the entire Sliquid Certified Expert Training Course. Your certificate has been issued and is ready to download from your portal.",
      t_label_issued_to: "Issued To",
      t_label_completed: "Completed",
      t_label_cert_number: "Certificate Number",
      t_cta: "View & Download Certificate",
      t_verify: "You can also verify this certificate at any time at",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Su certificado de Experto Certificado Sliquid",
      t_tagline: "Portal de Socios B2B",
      t_heading: "¡Ya es Experto Certificado Sliquid!",
      t_intro_before: "Felicidades,",
      t_intro_after: ". Completó con éxito todo el Curso de Capacitación de Experto Certificado Sliquid. Su certificado fue emitido y está listo para descargarse desde su portal.",
      t_label_issued_to: "Emitido a",
      t_label_completed: "Completado",
      t_label_cert_number: "Número de certificado",
      t_cta: "Ver y descargar el certificado",
      t_verify: "También puede verificar este certificado en cualquier momento en",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Votre certificat d’Expert certifié Sliquid",
      t_tagline: "Portail partenaires B2B",
      t_heading: "Vous êtes maintenant Expert certifié Sliquid!",
      t_intro_before: "Félicitations,",
      t_intro_after: ". Vous avez terminé avec succès l’ensemble du cours de formation Expert certifié Sliquid. Votre certificat a été émis et peut être téléchargé depuis votre portail.",
      t_label_issued_to: "Délivré à",
      t_label_completed: "Terminé le",
      t_label_cert_number: "Numéro de certificat",
      t_cta: "Voir et télécharger le certificat",
      t_verify: "Vous pouvez aussi vérifier ce certificat en tout temps à",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_register_confirm: {
    en: {
      t_subject: "Your Sliquid B2B Portal registration",
      t_tagline: "B2B Partner Portal",
      t_heading: "Welcome, {user_name}!",
      t_intro_before: "Thank you for registering with the",
      t_intro_after: ". Your account has been received and is currently under review by our team.",
      t_badge: "Pending Review",
      t_pending: "Our team will review your application and grant portal access shortly. You'll receive a confirmation email once your account is approved.",
      t_details_heading: "Your Registration Details",
      t_label_name: "Name",
      t_label_email: "Email",
      t_help: "If you have any questions in the meantime, feel free to reach out at",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Su registro en el Portal B2B de Sliquid",
      t_tagline: "Portal de Socios B2B",
      t_heading: "¡Bienvenido, {user_name}!",
      t_intro_before: "Gracias por registrarse en el",
      t_intro_after: ". Recibimos su cuenta y nuestro equipo la está revisando.",
      t_badge: "Pendiente de revisión",
      t_pending: "Nuestro equipo revisará su solicitud y le dará acceso al portal en breve. Recibirá un correo de confirmación cuando su cuenta sea aprobada.",
      t_details_heading: "Datos de su registro",
      t_label_name: "Nombre",
      t_label_email: "Correo electrónico",
      t_help: "Si tiene preguntas mientras tanto, no dude en escribirnos a",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Votre inscription au portail B2B de Sliquid",
      t_tagline: "Portail partenaires B2B",
      t_heading: "Bienvenue, {user_name}!",
      t_intro_before: "Merci de vous être inscrit au",
      t_intro_after: ". Nous avons bien reçu votre compte et notre équipe est en train de l’examiner.",
      t_badge: "En attente d’examen",
      t_pending: "Notre équipe examinera votre demande et vous donnera accès au portail sous peu. Vous recevrez un courriel de confirmation dès que votre compte sera approuvé.",
      t_details_heading: "Détails de votre inscription",
      t_label_name: "Nom",
      t_label_email: "Courriel",
      t_help: "Si vous avez des questions d’ici là, n’hésitez pas à nous écrire à",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_approved: {
    en: {
      t_subject: "Your Sliquid B2B Portal account is approved",
      t_tagline: "B2B Partner Portal",
      t_badge: "Account Approved",
      t_heading: "You're in, {user_name}!",
      t_intro: "Your Sliquid B2B Partner Portal account has been approved. You can now log in and access all the resources available to your account type.",
      t_label_role: "Account Type",
      t_cta: "Log In to Your Portal →",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Su cuenta del Portal B2B de Sliquid fue aprobada",
      t_tagline: "Portal de Socios B2B",
      t_badge: "Cuenta aprobada",
      t_heading: "¡Ya tiene acceso, {user_name}!",
      t_intro: "Su cuenta del Portal de Socios B2B de Sliquid fue aprobada. Ya puede iniciar sesión y acceder a todos los recursos disponibles para su tipo de cuenta.",
      t_label_role: "Tipo de cuenta",
      t_cta: "Iniciar sesión en su portal →",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Votre compte du portail B2B de Sliquid est approuvé",
      t_tagline: "Portail partenaires B2B",
      t_badge: "Compte approuvé",
      t_heading: "C’est fait, {user_name}!",
      t_intro: "Votre compte du portail partenaires B2B de Sliquid a été approuvé. Vous pouvez maintenant vous connecter et accéder à toutes les ressources offertes à votre type de compte.",
      t_label_role: "Type de compte",
      t_cta: "Se connecter au portail →",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_declined: {
    en: {
      t_subject: "An update on your Sliquid B2B Portal application",
      t_tagline: "B2B Partner Portal",
      t_heading: "An update on your application",
      t_intro: "Hi {user_name}, thank you for your interest in the Sliquid B2B Partner Portal. After reviewing your application, we're unable to approve portal access at this time.",
      t_body: "If you believe this is an error or would like to discuss your application, please reach out to our support team — we're happy to help.",
      t_cta: "Contact Support",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Novedades sobre su solicitud al Portal B2B de Sliquid",
      t_tagline: "Portal de Socios B2B",
      t_heading: "Novedades sobre su solicitud",
      t_intro: "Hola, {user_name}: gracias por su interés en el Portal de Socios B2B de Sliquid. Tras revisar su solicitud, por ahora no podemos aprobar el acceso al portal.",
      t_body: "Si cree que se trata de un error o desea hablar sobre su solicitud, comuníquese con nuestro equipo de soporte; con gusto le ayudaremos.",
      t_cta: "Contactar a soporte",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Mise à jour concernant votre demande au portail B2B de Sliquid",
      t_tagline: "Portail partenaires B2B",
      t_heading: "Mise à jour concernant votre demande",
      t_intro: "Bonjour {user_name}, merci de votre intérêt pour le portail partenaires B2B de Sliquid. Après examen de votre demande, nous ne sommes pas en mesure d’approuver l’accès au portail pour le moment.",
      t_body: "Si vous croyez qu’il s’agit d’une erreur ou souhaitez discuter de votre demande, communiquez avec notre équipe de soutien — nous serons heureux de vous aider.",
      t_cta: "Joindre le soutien",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_reward_confirm: {
    en: {
      t_subject: "Your Sliquid reward is on its way!",
      t_tagline: "B2B Partner Portal",
      t_badge: "Reward Submitted",
      t_heading: "Your reward is on the way, {user_name}!",
      t_intro: "We've received your reward claim. Our team will process and ship your items to the address on file. Keep an eye on your inbox for a shipping notification.",
      t_label_product: "Free Product",
      t_label_shirt: "T-Shirt Size",
      t_label_ship_to: "Ship To",
      t_update_before: "Need to update your shipping address? Contact",
      t_update_after: "as soon as possible.",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "¡Su recompensa de Sliquid va en camino!",
      t_tagline: "Portal de Socios B2B",
      t_badge: "Recompensa enviada",
      t_heading: "¡Su recompensa va en camino, {user_name}!",
      t_intro: "Recibimos su solicitud de recompensa. Nuestro equipo procesará su pedido y enviará los artículos a la dirección registrada. Esté atento a su bandeja de entrada: le avisaremos cuando se envíe.",
      t_label_product: "Producto gratis",
      t_label_shirt: "Talla de camiseta",
      t_label_ship_to: "Enviar a",
      t_update_before: "¿Necesita actualizar su dirección de envío? Escriba a",
      t_update_after: "lo antes posible.",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Votre récompense Sliquid est en route!",
      t_tagline: "Portail partenaires B2B",
      t_badge: "Récompense soumise",
      t_heading: "Votre récompense est en route, {user_name}!",
      t_intro: "Nous avons bien reçu votre demande de récompense. Notre équipe traitera la demande et expédiera vos articles à l’adresse inscrite. Surveillez votre boîte de réception pour l’avis d’expédition.",
      t_label_product: "Produit gratuit",
      t_label_shirt: "Taille de t-shirt",
      t_label_ship_to: "Livrer à",
      t_update_before: "Vous devez modifier votre adresse de livraison? Écrivez à",
      t_update_after: "dès que possible.",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_marketing_user: {
    en: {
      t_subject: "Your marketing asset request was received",
      t_tagline: "B2B Partner Portal",
      t_badge: "Request Received",
      t_heading: "We got your request, {user_name}!",
      t_intro: "Your marketing request has been submitted. Our team will review it and reach out to confirm details.",
      t_label_items: "Requested Items",
      t_help: "Questions about your request? Reach out at",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Recibimos su solicitud de materiales de marketing",
      t_tagline: "Portal de Socios B2B",
      t_badge: "Solicitud recibida",
      t_heading: "¡Recibimos su solicitud, {user_name}!",
      t_intro: "Su solicitud de marketing fue enviada. Nuestro equipo la revisará y se comunicará con usted para confirmar los detalles.",
      t_label_items: "Artículos solicitados",
      t_help: "¿Preguntas sobre su solicitud? Escríbanos a",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Nous avons bien reçu votre demande de matériel marketing",
      t_tagline: "Portail partenaires B2B",
      t_badge: "Demande reçue",
      t_heading: "Nous avons bien reçu votre demande, {user_name}!",
      t_intro: "Votre demande marketing a été envoyée. Notre équipe l’examinera et communiquera avec vous pour confirmer les détails.",
      t_label_items: "Articles demandés",
      t_help: "Des questions sur votre demande? Écrivez-nous à",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_medical_user: {
    en: {
      t_subject: "Your medical marketing request was received",
      t_tagline: "Health Practitioners Program",
      t_badge: "Request Received",
      t_heading: "We got your request, {user_name}!",
      t_intro: "Your medical marketing materials request has been submitted. Our health practitioners team will review it and reach out to confirm fulfillment and shipping details.",
      t_label_items: "Requested Items",
      t_help: "Questions about your request? Reach out at",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Recibimos su solicitud de marketing médico",
      t_tagline: "Programa para Profesionales de la Salud",
      t_badge: "Solicitud recibida",
      t_heading: "¡Recibimos su solicitud, {user_name}!",
      t_intro: "Su solicitud de materiales de marketing médico fue enviada. Nuestro equipo para profesionales de la salud la revisará y se comunicará con usted para confirmar la entrega y los detalles de envío.",
      t_label_items: "Artículos solicitados",
      t_help: "¿Preguntas sobre su solicitud? Escríbanos a",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Nous avons bien reçu votre demande de marketing médical",
      t_tagline: "Programme pour professionnels de la santé",
      t_badge: "Demande reçue",
      t_heading: "Nous avons bien reçu votre demande, {user_name}!",
      t_intro: "Votre demande de matériel de marketing médical a été envoyée. Notre équipe pour les professionnels de la santé l’examinera et communiquera avec vous pour confirmer l’exécution et les détails de livraison.",
      t_label_items: "Articles demandés",
      t_help: "Des questions sur votre demande? Écrivez-nous à",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  portal_password_reset: {
    en: {
      t_subject: "Reset your Sliquid Partner Portal password",
      t_tagline: "Partner Portal",
      t_heading: "Reset your password",
      t_greeting: "Hi {user_name},",
      t_intro: "We received a request to reset your password for your Sliquid Partner Portal account. Click the button below to choose a new password.",
      t_cta: "Reset Password",
      t_expiry_before: "This link expires in",
      t_expiry_duration: "1 hour",
      t_expiry_after: ". If you don't use it in time, you'll need to request a new one.",
      t_fallback: "If the button above doesn't work, copy and paste this URL into your browser:",
      t_ignore: "If you didn't request a password reset, you can safely ignore this email — your password won't change.",
      t_confidential: "Sliquid Partner Portal — Confidential",
      t_rights: "All rights reserved.",
    },
    es: {
      t_subject: "Restablezca su contraseña del Portal de Socios de Sliquid",
      t_tagline: "Portal de Socios",
      t_heading: "Restablezca su contraseña",
      t_greeting: "Hola, {user_name}:",
      t_intro: "Recibimos una solicitud para restablecer la contraseña de su cuenta del Portal de Socios de Sliquid. Haga clic en el botón de abajo para elegir una nueva contraseña.",
      t_cta: "Restablecer contraseña",
      t_expiry_before: "Este enlace vence en",
      t_expiry_duration: "1 hora",
      t_expiry_after: ". Si no lo usa a tiempo, deberá solicitar uno nuevo.",
      t_fallback: "Si el botón no funciona, copie y pegue esta dirección en su navegador:",
      t_ignore: "Si no solicitó restablecer su contraseña, puede ignorar este correo: su contraseña no cambiará.",
      t_confidential: "Portal de Socios de Sliquid — Confidencial",
      t_rights: "Todos los derechos reservados.",
    },
    fr: {
      t_subject: "Réinitialisez votre mot de passe du portail partenaires Sliquid",
      t_tagline: "Portail partenaires",
      t_heading: "Réinitialisez votre mot de passe",
      t_greeting: "Bonjour {user_name},",
      t_intro: "Nous avons reçu une demande de réinitialisation du mot de passe de votre compte du portail partenaires Sliquid. Cliquez sur le bouton ci-dessous pour choisir un nouveau mot de passe.",
      t_cta: "Réinitialiser le mot de passe",
      t_expiry_before: "Ce lien expire dans",
      t_expiry_duration: "1 heure",
      t_expiry_after: ". Si vous ne l’utilisez pas à temps, vous devrez en demander un nouveau.",
      t_fallback: "Si le bouton ne fonctionne pas, copiez et collez cette adresse dans votre navigateur :",
      t_ignore: "Si vous n’avez pas demandé de réinitialisation, vous pouvez ignorer ce courriel — votre mot de passe ne changera pas.",
      t_confidential: "Portail partenaires Sliquid — Confidentiel",
      t_rights: "Tous droits réservés.",
    },
  },
  portal_asset_broadcast: {
    en: {
      t_subject: "New in the Sliquid Product Library: {asset_name}",
      t_tagline: "B2B Partner Portal",
      t_badge: "New in Product Library",
      t_heading: "New assets just dropped, {user_name}!",
      t_intro: "Fresh content is now available in your Product Library. Head to the portal to preview and download it for your store.",
      t_label_asset: "Asset",
      t_label_brand: "Brand",
      t_cta: "View Product Library →",
      t_footer_sent: "This email was sent by the Sliquid B2B Partner Portal.",
      t_footer_questions: "Questions? Contact",
    },
    es: {
      t_subject: "Nuevo en la Biblioteca de Productos de Sliquid: {asset_name}",
      t_tagline: "Portal de Socios B2B",
      t_badge: "Nuevo en la Biblioteca de Productos",
      t_heading: "¡Hay recursos nuevos, {user_name}!",
      t_intro: "Hay contenido nuevo disponible en su Biblioteca de Productos. Visite el portal para verlo y descargarlo para su tienda.",
      t_label_asset: "Recurso",
      t_label_brand: "Marca",
      t_cta: "Ver la Biblioteca de Productos →",
      t_footer_sent: "Este correo fue enviado por el Portal de Socios B2B de Sliquid.",
      t_footer_questions: "¿Preguntas? Escriba a",
    },
    fr: {
      t_subject: "Nouveauté dans la bibliothèque de produits Sliquid : {asset_name}",
      t_tagline: "Portail partenaires B2B",
      t_badge: "Nouveauté dans la bibliothèque de produits",
      t_heading: "De nouvelles ressources sont arrivées, {user_name}!",
      t_intro: "Du nouveau contenu est offert dans votre bibliothèque de produits. Rendez-vous sur le portail pour le consulter et le télécharger pour votre magasin.",
      t_label_asset: "Ressource",
      t_label_brand: "Marque",
      t_cta: "Voir la bibliothèque de produits →",
      t_footer_sent: "Ce courriel a été envoyé par le portail partenaires B2B de Sliquid.",
      t_footer_questions: "Des questions? Écrivez à",
    },
  },
  b2b_contact_reply: {
    en: {
      t_subject: "We received your message — Sliquid",
      t_tagline: "B2B Partnerships",
      t_heading: "Thanks for reaching out, {to_name}!",
      t_intro_before: "We've received your message and a member of our B2B team will review it shortly. We typically respond within",
      t_intro_duration: "2 business days",
      t_portal: "In the meantime, you're welcome to explore our partner portal where you can access product information, marketing assets, and training resources.",
      t_cta: "Visit Partner Portal",
      t_next_heading: "What happens next",
      t_step1: "Our team reviews your inquiry and matches it to the right contact.",
      t_step2: "We'll reach out by email (or phone if you provided a number).",
      t_step3: "You'll receive a tailored proposal or follow-up based on your inquiry type.",
      t_footer_reply: "Questions? Reply to this email or contact",
      t_rights: "All rights reserved.",
    },
    es: {
      t_subject: "Recibimos su mensaje — Sliquid",
      t_tagline: "Alianzas B2B",
      t_heading: "¡Gracias por escribirnos, {to_name}!",
      t_intro_before: "Recibimos su mensaje y un miembro de nuestro equipo B2B lo revisará en breve. Normalmente respondemos en un plazo de",
      t_intro_duration: "2 días hábiles",
      t_portal: "Mientras tanto, puede explorar nuestro portal de socios, donde encontrará información de productos, materiales de marketing y recursos de capacitación.",
      t_cta: "Visitar el portal de socios",
      t_next_heading: "Próximos pasos",
      t_step1: "Nuestro equipo revisa su consulta y la asigna al contacto adecuado.",
      t_step2: "Nos comunicaremos con usted por correo electrónico (o por teléfono si nos dio un número).",
      t_step3: "Recibirá una propuesta o un seguimiento personalizado según el tipo de consulta.",
      t_footer_reply: "¿Preguntas? Responda a este correo o escriba a",
      t_rights: "Todos los derechos reservados.",
    },
    fr: {
      t_subject: "Nous avons bien reçu votre message — Sliquid",
      t_tagline: "Partenariats B2B",
      t_heading: "Merci de nous avoir écrit, {to_name}!",
      t_intro_before: "Nous avons bien reçu votre message et un membre de notre équipe B2B l’examinera sous peu. Nous répondons généralement dans un délai de",
      t_intro_duration: "2 jours ouvrables",
      t_portal: "D’ici là, vous pouvez explorer notre portail partenaires, qui offre de l’information sur les produits, du matériel marketing et des ressources de formation.",
      t_cta: "Visiter le portail partenaires",
      t_next_heading: "Prochaines étapes",
      t_step1: "Notre équipe examine votre demande et l’achemine à la bonne personne.",
      t_step2: "Nous communiquerons avec vous par courriel (ou par téléphone si vous avez fourni un numéro).",
      t_step3: "Vous recevrez une proposition ou un suivi adapté selon le type de demande.",
      t_footer_reply: "Des questions? Répondez à ce courriel ou écrivez à",
      t_rights: "Tous droits réservés.",
    },
  },
  b2b_retailer_confirm: {
    en: {
      t_subject: "Your Sliquid Retailer / Distributor Application",
      t_tagline: "Retailer & Distributor Program",
      t_badge: "Application Received",
      t_heading: "Thanks for applying, {contact_name}!",
      t_intro_before: "We've received your application for",
      t_intro_after: "to become a Sliquid retailer or distributor. A member of our sales team will review your submission and reach out to you shortly.",
      t_label_brands: "Brands You Selected",
      t_next_heading: "What happens next",
      t_step1_before: "Our sales team reviews your application — typically within",
      t_step1_duration: "2–3 business days",
      t_step2: "We'll reach out via email or phone to discuss next steps and answer any questions.",
      t_step3: "Once approved, you'll receive access to the Sliquid B2B Partner Portal with ordering, training, and marketing resources.",
      t_cta: "Learn More About Sliquid B2B",
      t_help: "Have questions in the meantime? Contact our sales team at",
      t_submitted: "Submitted via",
      t_rights: "All rights reserved.",
    },
    es: {
      t_subject: "Su solicitud de minorista / distribuidor de Sliquid",
      t_tagline: "Programa de Minoristas y Distribuidores",
      t_badge: "Solicitud recibida",
      t_heading: "¡Gracias por su solicitud, {contact_name}!",
      t_intro_before: "Recibimos la solicitud de",
      t_intro_after: "para convertirse en minorista o distribuidor de Sliquid. Un miembro de nuestro equipo de ventas revisará su solicitud y se comunicará con usted en breve.",
      t_label_brands: "Marcas seleccionadas",
      t_next_heading: "Próximos pasos",
      t_step1_before: "Nuestro equipo de ventas revisa su solicitud, normalmente en un plazo de",
      t_step1_duration: "2 a 3 días hábiles",
      t_step2: "Nos comunicaremos por correo electrónico o por teléfono para hablar de los próximos pasos y responder sus preguntas.",
      t_step3: "Una vez aprobada, recibirá acceso al Portal de Socios B2B de Sliquid con recursos de pedidos, capacitación y marketing.",
      t_cta: "Conozca más sobre Sliquid B2B",
      t_help: "¿Tiene preguntas mientras tanto? Comuníquese con nuestro equipo de ventas en",
      t_submitted: "Enviado desde",
      t_rights: "Todos los derechos reservados.",
    },
    fr: {
      t_subject: "Votre demande de détaillant / distributeur Sliquid",
      t_tagline: "Programme des détaillants et distributeurs",
      t_badge: "Demande reçue",
      t_heading: "Merci pour votre demande, {contact_name}!",
      t_intro_before: "Nous avons bien reçu la demande de",
      t_intro_after: "pour devenir détaillant ou distributeur Sliquid. Un membre de notre équipe des ventes examinera votre demande et communiquera avec vous sous peu.",
      t_label_brands: "Marques sélectionnées",
      t_next_heading: "Prochaines étapes",
      t_step1_before: "Notre équipe des ventes examine votre demande — généralement dans un délai de",
      t_step1_duration: "2 à 3 jours ouvrables",
      t_step2: "Nous communiquerons avec vous par courriel ou par téléphone pour discuter des prochaines étapes et répondre à vos questions.",
      t_step3: "Une fois la demande approuvée, vous aurez accès au portail partenaires B2B de Sliquid et à ses ressources de commande, de formation et de marketing.",
      t_cta: "En savoir plus sur Sliquid B2B",
      t_help: "Des questions d’ici là? Communiquez avec notre équipe des ventes à",
      t_submitted: "Soumis via",
      t_rights: "Tous droits réservés.",
    },
  },
  b2b_retailer_checkin_confirm: {
    en: {
      t_subject: "Thanks for checking in, {contact_name} — {reference_number}",
      t_tagline: "Partner Check-In",
      t_reference: "Reference",
      t_heading: "Thank you, {contact_name}.",
      t_intro_before: "We got your check-in for",
      t_intro_after: "— and more than that, thank you for the shelf space. Partners like you are the reason a small, ingredient-obsessed brand got to have a twenty-year run.",
      t_followup: "will follow up with you shortly.",
      t_asked_heading: "What you asked us for",
      t_next_heading: "What happens next",
      t_step1_before: "Your contact reviews the check-in — usually within",
      t_step1_duration: "1–2 business days",
      t_step2: "Anything you asked for — marketing materials, product images, training — gets sent your way.",
      t_step3_before: "Quote",
      t_step3_after: "in any reply and we'll pull your check-in straight up.",
      t_cta: "Open the Partner Portal",
      t_help: "Need something sooner? Email",
      t_submitted: "Submitted via",
      t_rights: "All rights reserved.",
    },
    es: {
      t_subject: "Gracias por registrarse, {contact_name} — {reference_number}",
      t_tagline: "Registro de socios",
      t_reference: "Referencia",
      t_heading: "Gracias, {contact_name}.",
      t_intro_before: "Recibimos el registro de",
      t_intro_after: "y, más que eso, gracias por el espacio en sus anaqueles. Socios como usted son la razón por la que una marca pequeña y obsesionada con los ingredientes ha llegado a cumplir veinte años.",
      t_followup: "se comunicará con usted en breve.",
      t_asked_heading: "Lo que nos solicitó",
      t_next_heading: "Próximos pasos",
      t_step1_before: "Su contacto revisa el registro, normalmente en un plazo de",
      t_step1_duration: "1 a 2 días hábiles",
      t_step2: "Todo lo que solicitó (materiales de marketing, imágenes de productos, capacitación) se le enviará.",
      t_step3_before: "Mencione",
      t_step3_after: "en cualquier respuesta y encontraremos su registro de inmediato.",
      t_cta: "Abrir el portal de socios",
      t_help: "¿Necesita algo antes? Escriba a",
      t_submitted: "Enviado desde",
      t_rights: "Todos los derechos reservados.",
    },
    fr: {
      t_subject: "Merci pour votre suivi, {contact_name} — {reference_number}",
      t_tagline: "Suivi des partenaires",
      t_reference: "Référence",
      t_heading: "Merci, {contact_name}.",
      t_intro_before: "Nous avons bien reçu le suivi de",
      t_intro_after: "— et surtout, merci pour l’espace sur vos tablettes. Ce sont des partenaires comme vous qui ont permis à une petite marque obsédée par les ingrédients de durer vingt ans.",
      t_followup: "communiquera avec vous sous peu.",
      t_asked_heading: "Ce que vous nous avez demandé",
      t_next_heading: "Prochaines étapes",
      t_step1_before: "Votre personne-ressource examine le suivi — généralement dans un délai de",
      t_step1_duration: "1 à 2 jours ouvrables",
      t_step2: "Tout ce que vous avez demandé — matériel marketing, images de produits, formation — vous sera envoyé.",
      t_step3_before: "Indiquez",
      t_step3_after: "dans toute réponse et nous retrouverons votre suivi immédiatement.",
      t_cta: "Ouvrir le portail partenaires",
      t_help: "Besoin de quelque chose plus tôt? Écrivez à",
      t_submitted: "Soumis via",
      t_rights: "Tous droits réservés.",
    },
  },
} as const satisfies Record<string, Record<Language, Copy>>

export type EmailTemplateId = keyof typeof EMAIL_COPY

/** Role names as shown in the approval email (mirrors the clients' common:roles.*). */
export const ROLE_LABELS: Record<Language, Record<string, string>> = {
  en: { tier1: "Retail Store Employee", tier2: "Retail Management", tier3: "Distributor", tier4: "Prospect", tier5: "Admin", tier6: "Medical Partner", tier7: "Media", tier8: "Legal (Read-Only)" },
  es: { tier1: "Empleado de tienda minorista", tier2: "Gerencia minorista", tier3: "Distribuidor", tier4: "Prospecto", tier5: "Administrador", tier6: "Socio médico", tier7: "Medios", tier8: "Legal (solo lectura)" },
  fr: { tier1: "Employé de magasin", tier2: "Direction de magasin", tier3: "Distributeur", tier4: "Prospect", tier5: "Administrateur", tier6: "Partenaire médical", tier7: "Médias", tier8: "Juridique (lecture seule)" },
}

/** Fallbacks for optional form answers, used inside translated sentences. */
export const DEFAULTS: Record<Language, { pointOfContact: string; interests: string }> = {
  en: { pointOfContact: "a member of our sales team", interests: "None selected" },
  es: { pointOfContact: "Un miembro de nuestro equipo de ventas", interests: "Ninguno seleccionado" },
  fr: { pointOfContact: "Un membre de notre équipe des ventes", interests: "Aucune sélection" },
}

/** Replace `{name}` placeholders; unknown placeholders are left as-is. */
export function interpolate(text: string, vars: Record<string, string>): string {
  return text.replace(/\{(\w+)\}/g, (whole, name: string) => (name in vars ? vars[name] : whole))
}

/**
 * `lang` + every `t_*` variable for a template in the given language, with
 * `{placeholders}` filled from `vars`. Spread into the EmailJS params alongside
 * the template's existing variables.
 */
export function emailVars(templateId: EmailTemplateId, lang: Language, vars: Record<string, string> = {}): Record<string, string> {
  const copy: Copy = EMAIL_COPY[templateId][lang]
  const out: Record<string, string> = { lang }
  for (const [key, value] of Object.entries(copy)) out[key] = interpolate(value, vars)
  return out
}
